steps:
  - name: google/cloud-sdk
    entrypoint: "/bin/bash"
    args:
    - "-c"
    - |
      set -x
      set -e
      set -o pipefail
      date
      if gsutil stat gs://debezium-maven-repo/$REPO_NAME.tar
        then gsutil cp gs://debezium-maven-repo/$REPO_NAME.tar - | tar -xf -
      fi
      date
  - name: "eu.gcr.io/$PROJECT_ID/java17-maven3-8-gcp-alpine:latest"
    secretEnv:
      - NEXUS_USERNAME
      - NEXUS_PASSWORD
      - SONAR_TOKEN
    entrypoint: "/bin/bash"
    args:
    - "-c"
    - |
      set -x
      set -e
      set -o pipefail
      date

      echo copy config into HOME
      cp -ar /root/.docker $$HOME

      date

      echo build snapshot version

      mvn -B -P jhc.snapshot -no-transfer-progress -DskipNexusStagingDeployMojo=true -Drepository.project=$PROJECT_ID \
         -Dsonar.qualitygate.wait=${_FAIL_ON_SONAR} -Dsonar.host.url=${_SONAR_SERVER}  -Dsonar.login=$${SONAR_TOKEN} \
         -Dmaven.repo.local=./_m2/repository/ -DskipITs -Dbuild=SNAPSHOT -DfailIfNoTests=false deploy sonar:sonar

      date
    timeout: "8200s"
  - name: google/cloud-sdk
    entrypoint: "/bin/bash"
    args:
    - "-c"
    - |
      set -x
      set -e
      set -o pipefail
      date
      tar -cf - ./_m2/ | gsutil cp - gs://debezium-maven-repo/$REPO_NAME.tar
      date
timeout: "8200s"

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/nexus_user/versions/latest
      env: NEXUS_USERNAME
    - versionName: projects/${PROJECT_ID}/secrets/nexus_password/versions/latest
      env: NEXUS_PASSWORD
    - versionName: projects/${PROJECT_ID}/secrets/sonar-token/versions/latest
      env: SONAR_TOKEN