startDelaySeconds: 0
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
rules:
- pattern : "kafka.connect<type=connect-worker-metrics><>([^:>]+):"
  name: "kafka_connect_worker_metrics_$1"
- pattern : "kafka.connect<type=connect-metrics, client-id=([^:>]+)><>(connection-count|connection-creation-rate|connector-count|connector-startup-attempts-total|connector-startup-failure-total|request-rate|request-size-avg|response-rate|select-rate|task-count|task-startup-attempts-total|task-startup-failure-total)"
  name: "kafka_connect_metrics_$2"
  labels:
    client: "$1"
- pattern: "debezium.([^<]+)<type=connector-metrics, context=([^,>]+), server=([^,>]+)><>([^:]+)"
  name: "debezium_metrics_$4"
  labels:
    connector: "$1"
    server: "$3"
    context: "$2"
- pattern: "kafka.producer<type=producer-metrics, client-id=([^,>]+)><>(buffer-available-bytes|buffer-exhausted-rate|connection-count|connection-creation-rate|metadata-age|produce-throttle-time-avg|record-error-rate|record-queue-time-avg|record-retry-rate|record-send-rate|record-size-avg|requests-in-flight|request-latency-avg|response-rate|select-rate|txn-send-offsets-time-ns-total|waiting-threads)"
  name: "kafka_producer_$2"
  labels:
    client: "$1" 
- pattern: "kafka.consumer<type=consumer-metrics, client-id=([^,>]+)><>(connection-count|connection-creation-rate|incoming-byte-rate|io-wait-time-ns-avg|last-poll-seconds-ago|outgoing-byte-rate|poll-idle-ratio-avg|request-rate|request-size-avg|response-rate|select-rate)"
  name: "kafka_consumer_$2"
  labels:
    client: "$1"